# Generated by Django 4.1.1 on 2022-09-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_account_alter_userinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='VIP number')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], verbose_name='level')),
                ('status', models.SmallIntegerField(choices=[(1, 'for sale'), (2, 'sold')], verbose_name='status')),
            ],
        ),
    ]
