# Generated by Django 4.1.1 on 2022-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_vipnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipnumber',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='vipnumber',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'for sale'), (2, 'sold')], default=1, verbose_name='status'),
        ),
    ]
