# Generated by Django 4.1.1 on 2022-09-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'normal'), (2, 'urgent')], default=1, verbose_name='level')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='responsible person')),
            ],
        ),
    ]
